git:
  depth: false
language: java
jdk: openjdk8
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.sonar/cache"
    - "$HOME/.sonar/native-sonar-scanner"
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"
    - "$HOME/.sonar/cache"
before_install:
# Change Travis install phase to only resolve dependencies needed to run the build.
# Otherwise it would run `mvn install`, which results in doing some Maven phases twice (validate, compile, jar, ...).
# https://docs.travis-ci.com/user/languages/java/#projects-using-maven
#
# We also want to avoid Maven's install phase to prevent from writing to ~/.m2/repository, which is cached.
install: mvn dependency:go-offline -Pjacoco,sonar --show-version
# do not install to avoid dirtying the cache
script: mvn verify -Pjacoco,sonar --show-version

after_script: git diff HEAD --exit-code
